futebola/urls.py
from django.urls import re_path

from . import views

app_name = "futebola"

urlpatterns = [
    # ex: /futebola/
    re_path(r"^$", views.index, name="index"),
    # ex: /futebola/5
    re_path(r"^(?P<epoca_num>[0-9]+)/$", views.index, name="index"),
    # ex: /futebola/jogo/5/
    re_path(r"^jogo/(?P<jogo_id>[0-9]+)/$", views.jogo, name="jogo"),
    # ex: /futebola/jogador/
    re_path(r"^jogador/$", views.jogador, name="jogador"),
    # ex: /futebola/jogador/5/
    re_path(r"^jogador/(?P<jogador_id>[0-9]+)/$", views.jogador, name="jogador"),
    # ex: /futebola/regras/
    re_path(r"^regras/$", views.regras, name="regras"),
    # ex: /futebola/regras/5/
    re_path(r"^regras/(?P<epoca_num>[0-9]+)/$", views.regras, name="regras"),
    # ex: /futebola/tops/
    re_path(r"^tops/$", views.tops, name="tops"),
    # ex: /futebola/tops/5/
    re_path(r"^tops/(?P<epoca_num>[0-9]+)/$", views.tops, name="tops"),
    # ex: /futebola/gerar/
    re_path(r"^gerar/", views.gerarEquipas, name="gerarEquipas"),
    # ex: /futebola/criar-equipas/
    re_path(r"^criar-equipas/", views.criarEquipas, name="criarEquipas"),
    # ex: /futebola/numepoca/
    re_path(r"^numepoca/$", views.numerosEpoca, name="numerosEpoca"),
    # ex: /futebola/numepoca/5/
    re_path(
        r"^numepoca/(?P<epoca_num>[0-9]+)/$", views.numerosEpoca, name="numerosEpoca"
    ),
    # ex: /futebola/penalizacoes/
    re_path(r"^penalizacoes/$", views.penalizacoes, name="penalizacoes"),
    # ex: /futebola/penalizacoes/5/
    re_path(
        r"^penalizacoes/(?P<epoca_num>[0-9]+)/$",
        views.penalizacoes,
        name="penalizacoes",
    ),
]

futebola_labs/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, re_path, include

urlpatterns = (
    [
        path("admin/", admin.site.urls),
        re_path(r"^", include("futebola.urls")),
    ]
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [re_path(r"^__debug__/", include(debug_toolbar.urls))] + urlpatterns

futebola/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseNotFound
from .models import Jogador, Jogo, Ficha_de_jogo, Epoca, Penalizacao
import datetime
import json
from django.urls import reverse


def index(request, epoca_num=0):
    if not epoca_num:
        epoca_num = Epoca.objects.order_by("-epoca_id").first().numeracao_epoca
    epocas = Epoca.objects.all()
    epoca = get_object_or_404(Epoca, numeracao_epoca=epoca_num)

    old_lista_jogos = Jogo.objects.filter(epoca__numeracao_epoca=epoca_num).order_by(
        "-data"
    )

    lista_jogos = []
    for idx, jogo in enumerate(old_lista_jogos):
        if idx > 4:
            break
        if jogo.data < datetime.date.today():
            lista_jogos.append(jogo)

    lista_prox_jogos = []
    for idx, jogo in enumerate(old_lista_jogos):
        if idx > 4:
            break
        if jogo.data >= datetime.date.today():
            lista_prox_jogos.append(jogo)

    lista_clubes = []
    for item in Jogador.lista_clubes():
        for k, v in item.items():
            lista_clubes.append([k, v])

    lista_jogadores = epoca.lista_jogs(
        "-pontuacao, -golos, -assistencias, -jogos, -vitorias, derrotas"
    )
    lista_jog_mais_reg = epoca.lista_jogs("-jogos")[:5]
    lista_jog_mais_gol = epoca.lista_jogs("-golos, jogos, -vitorias")[:5]
    lista_jog_mais_ass = epoca.lista_jogs("-assistencias, jogos, -vitorias")[:5]
    cuurl = reverse("futebola:index")
    is_home = True

    context = {
        "epocas": epocas,
        "epoca": epoca,
        "epoca_num": epoca_num,
        "lista_jogadores": lista_jogadores,
        "lista_jog_mais_reg": lista_jog_mais_reg,
        "lista_jogos": lista_jogos,
        "lista_prox_jogos": lista_prox_jogos,
        "lista_clubes": lista_clubes,
        "lista_jog_mais_gol": lista_jog_mais_gol,
        "lista_jog_mais_ass": lista_jog_mais_ass,
        "cuurl": cuurl,
        "is_home": is_home,
    }

    return render(request, "futebola/index.html", context)


def jogo(request, jogo_id):
    jogo = get_object_or_404(Jogo, jogo_id=jogo_id)

    lista_equipa = jogo.lista_equipa

    context = {
        "jogo": jogo,
        "lista_equipa": lista_equipa,
        "bonuses_list": jogo.bonuses_list,
        "penalties_list": jogo.penalties_list,
    }

    return render(request, "futebola/jogo.html", context)


def jogador(request, jogador_id):
    epoca_num = Epoca.objects.order_by("-epoca_id").first().numeracao_epoca

    jogador = get_object_or_404(Jogador, jogador_id=jogador_id)
    epocas_obj = Epoca.objects.order_by("-epoca_id")

    fichas_jogo = (
        Ficha_de_jogo.objects.select_related("jogo")
        .filter(jogador=jogador, jogo__epoca__numeracao_epoca=epoca_num)
        .order_by("-ficha_id")[:10]
    )
    lista_jogos = [ficha.jogo for ficha in fichas_jogo]

    context = {
        "epocas_obj": epocas_obj,
        "jogador": jogador,
        "lista_jogos": lista_jogos,
        "cuurl": reverse("futebola:jogador"),
    }

    return render(request, "futebola/jogador.html", context)


def numerosEpoca(
    request, epoca_num=Epoca.objects.order_by("-epoca_id").first().numeracao_epoca
):
    epocas = Epoca.objects.all()
    epoca = get_object_or_404(Epoca, numeracao_epoca=epoca_num)

    media_golos_jogador = epoca.media_golos_jogador()
    media_assist_jogador = epoca.media_assist_jogador()
    percent_vitorias_jogador = epoca.percentVitorias()
    percent_derrotas_jogador = epoca.percentDerrotas()
    mais_jogos_jogador = epoca.lista_jogs("-jogos")[0]
    vit_consec_jogador = epoca.vitoriasConsec()[0]

    context = {
        "epocas": epocas,
        "epoca": epoca,
        "media_golos_jogador": media_golos_jogador,
        "media_assist_jogador": media_assist_jogador,
        "percent_vitorias_jogador": percent_vitorias_jogador,
        "percent_derrotas_jogador": percent_derrotas_jogador,
        "mais_jogos_jogador": mais_jogos_jogador,
        "vit_consec_jogador": vit_consec_jogador,
        "cuurl": reverse("futebola:numerosEpoca"),
    }

    return render(request, "futebola/numEpoca.html", context)


def regras(
    request, epoca_num=Epoca.objects.order_by("-epoca_id").first().numeracao_epoca
):
    epocas = Epoca.objects.all()
    epoca = get_object_or_404(Epoca, numeracao_epoca=epoca_num)

    context = {
        "epocas": epocas,
        "epoca": epoca,
        "cuurl": reverse("futebola:regras"),
    }

    return render(request, "futebola/regras.html", context)


def tops(
    request, epoca_num=Epoca.objects.order_by("-epoca_id").first().numeracao_epoca
):
    epocas = Epoca.objects.all()
    epoca = get_object_or_404(Epoca, numeracao_epoca=epoca_num)
    lista_jog_mais_reg = epoca.lista_jogs("-jogos")[:5]
    lista_jog_mais_gol = epoca.lista_jogs("-golos, jogos, -vitorias")[:5]
    lista_jog_mais_ass = epoca.lista_jogs("-assistencias, jogos, -vitorias")[:5]
    lista_jog_mais_vit = epoca.lista_jogs("-vitorias, jogos")[:5]
    lista_jog_mais_comb = epoca.lista_jogs("-combinado")[:5]
    lista_jog_golos_sof = epoca.media_golos_sofridos()[:5]

    for jog in lista_jog_mais_comb:
        soma = jog["golos"] + jog["assistencias"]
        jog["combinado"] = soma

    lista_jog_mais_comb = sorted(
        lista_jog_mais_comb, key=lambda k: k["combinado"], reverse=True
    )

    context = {
        "epocas": epocas,
        "epoca": epoca,
        "cuurl": reverse("futebola:tops"),
        "lista_jog_mais_gol": lista_jog_mais_gol,
        "lista_jog_mais_ass": lista_jog_mais_ass,
        "lista_jog_mais_reg": lista_jog_mais_reg,
        "lista_jog_mais_vit": lista_jog_mais_vit,
        "lista_jog_mais_comb": lista_jog_mais_comb,
        "lista_jog_golos_sof": lista_jog_golos_sof,
    }

    return render(request, "futebola/tops.html", context)


def penalizacoes(
    request, epoca_num=Epoca.objects.order_by("-epoca_id").first().numeracao_epoca
):
    epocas = Epoca.objects.all()
    epoca = get_object_or_404(Epoca, numeracao_epoca=epoca_num)
    penalizacoes = Penalizacao.objects.filter(
        epoca__numeracao_epoca=epoca_num
    ).order_by("-data")

    context = {
        "epocas": epocas,
        "epoca": epoca,
        "penalizacoes": penalizacoes,
        "cuurl": reverse("futebola:penalizacoes"),
    }

    return render(request, "futebola/penalizacoes.html", context)


def gerarEquipas(request):
    lista_jogadores = Jogador.objects.order_by("nome")
    lista_jogadores = sorted(lista_jogadores, key=lambda t: t.nota(), reverse=True)

    context = {"lista_jogadores": lista_jogadores}

    if request.method == "GET":
        return render(request, "futebola/gerarEquipas.html", context)
    else:
        ar = []
        ints = []
        post_list = request.POST.copy()
        for item in post_list:
            try:
                obj = {item: int(post_list[item])}
                ar.append(obj)
                ints.append(int(post_list[item]))
            except Exception:
                continue

        vals1, vals2 = team(ints)

        team1 = []
        team2 = []

        for x in vals1:
            for y in post_list:
                try:
                    if x == int(post_list[y]):
                        team1.append({y: post_list[y]})
                        del post_list[y]
                        break
                except Exception:
                    continue
        for x in vals2:
            for y in post_list:
                try:
                    if x == int(post_list[y]):
                        team2.append({y: post_list[y]})
                        del post_list[y]
                        break
                except Exception:
                    continue

        equipa1 = []
        equipa2 = []
        sume1 = 0
        sume2 = 0

        for x in team1:
            equipa1.append(
                get_object_or_404(Jogador, jogador_id=int(list(x.keys())[0]))
            )
            sume1 += int(list(x.values())[0])

        for x in team2:
            equipa2.append(
                get_object_or_404(Jogador, jogador_id=int(list(x.keys())[0]))
            )
            sume2 += int(list(x.values())[0])

        context = {
            "equipa1": equipa1,
            "equipa2": equipa2,
            "somae1": sume1,
            "somae2": sume2,
            "cuurl": reverse("futebola:gerarEquipas"),
        }

        # return JsonResponse(post_list, safe=False)
        return render(request, "futebola/verEquipasGeradas.html", context)


def criarEquipas(request):

    if request.method == "POST":

        data = json.loads(request.body)

        novoJogo = Jogo(
            local=data.get("local"), epoca=Epoca.objects.order_by("-epoca_id").first()
        )
        novoJogo.save()

        for jogadorId in data.get("equipaA"):
            ficha = Ficha_de_jogo(
                jogador=Jogador.objects.get(pk=jogadorId),
                equipa="Equipa_A",
                jogo=novoJogo,
            )
            ficha.save()

        for jogadorId in data.get("equipaB"):
            ficha = Ficha_de_jogo(
                jogador=Jogador.objects.get(pk=jogadorId),
                equipa="Equipa_B",
                jogo=novoJogo,
            )
            ficha.save()

        return HttpResponse(novoJogo.jogo_id)

    return HttpResponseNotFound("Método incompatível")


def team(t):
    iterations = range(2, int(len(t) / 2 + 1))

    totalscore = sum(t)
    halftotalscore = totalscore / 2.0

    oldmoves = {}

    for p in t:
        people_left = t[:]
        people_left.remove(p)
        oldmoves[p] = people_left

    if iterations == []:
        solution = min(
            map(lambda i: (abs(float(i) - halftotalscore), i), oldmoves.keys())
        )
        return (solution[1], sum(oldmoves[solution[1]]), oldmoves[solution[1]])

    for n in iterations:
        newmoves = {}
        for total, roster in oldmoves.items():

futebola/templates/futebola/gerarEquipas.html
{% extends "futebola/layout.html" %}

{% block content %}
<div class="row">
    <div class="col-sm-12">
        <div class="panel panel-default">
            <div class="panel-body" style="overflow-y: scroll;">
                <form action="/gerar/" method="post">{% csrf_token %}
                    {% if lista_jogadores %}
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th>Nome</th>
                                <th>G.R</th>
                                <th>Def</th>
                                <th>Vel</th>
                                <th>Res</th>
                                <th>For</th>
                                <th>Gar</th>
                                <th>Pos</th>
                                <th>Pas</th>
                                <th>Tec</th>
                                <th>Atq</th>
                                <th>Rlo</th>
                                <th>Fin</th>
                                <th>Exp</th>
                                <th>Nota</th>
                                <th>Moral</th>
                                <th>Nota Final</th>
                                <th style="text-align:center;">Sel.</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for jogador in lista_jogadores %}
                            <tr>
                                <td><a href="{% url 'futebola:jogador' jogador.jogador_id %}">{{ jogador }}</a></td>
                                <td>{{ jogador.guarda_redes }}</td>
                                <td>{{ jogador.defesa }}</td>
                                <td>{{ jogador.velocidade }}</td>
                                <td>{{ jogador.resistencia }}</td>
                                <td>{{ jogador.forca }}</td>
                                <td>{{ jogador.garra }}</td>
                                <td>{{ jogador.posicionamento }}</td>
                                <td>{{ jogador.passe }}</td>
                                <td>{{ jogador.tecnica }}</td>
                                <td>{{ jogador.ataque }}</td>
                                <td>{{ jogador.remates_longe }}</td>
                                <td>{{ jogador.finalizacao }}</td>
                                <td>{{ jogador.experiencia }}</td>
                                <td><b>{{ jogador.nota }}</b></td>
                                <td><b>{{ jogador.moral }}</b></td>
                                <td><b>{{ jogador.nota_final }}</b></td>
                                <td style="text-align:center;"><input id="{{ jogador.jogador_id }}" type="checkbox"
                                        name="{{ jogador.jogador_id }}" value="{{ jogador.nota_final }}"></td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                    <div class="row">
                        <div class="col-sm-2 col-sm-offset-9">
                            <input type="submit" class="btn btn-default" value="Gerar Equipas...">
                        </div>
                    </div>
                </form>
                {% else %}
                Sem dados para mostrar!
                {% endif %}
            </div>
        </div>
    </div>
    {% endblock %}

futebola/templates/futebola/index.html
{% extends "futebola/layout.html" %}

{% block content %}
<div class="row">
    <div class="col-sm-12">
    <div class="panel panel-default">
        <div class="panel-heading">Ranking Jogadores</div>
        <div class="panel-body" style="overflow-y: scroll; height: 400px; {% if lista_jogadores %} padding:0; {% else %} text-align: center; {% endif %}">
        {% if lista_jogadores %}
                <table class="table table-striped table-responsive" style="margin-bottom:0px;border:0;">
                    <thead>
                        <tr>
                            <th style="padding-left:2px;padding-right:2px;text-align:center;">#</th>
                            <th style="padding-left:2px;padding-right:2px;">Nome</th>
                            <th style="padding-left:2px;padding-right:2px;text-align:center;">Jgs</th>
                            <th style="padding-left:2px;padding-right:2px;text-align:center;">Vit</th>
                            <th style="padding-left:2px;padding-right:2px;text-align:center;">Emp</th>
                            <th style="padding-left:2px;padding-right:2px;text-align:center;">Der</th>
                            <th style="padding-left:2px;padding-right:2px;text-align:center;">Gls</th>
                            <th style="padding-left:2px;padding-right:2px;text-align:center;">Ass</th>
                            <th style="padding-left:3px;padding-right:3px;text-align:center;">Pts</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for jogador in lista_jogadores %}
                        <tr>
                            <td style="padding-left:2px;padding-right:2px;text-align:center;">{{ forloop.counter }}º</td>
                            <td style="padding-left:2px;padding-right:2px;"><a href="{% url 'futebola:jogador' jogador.jogador_id %}">{{ jogador.nome }}</a></td>
                            <td style="padding-left:2px;padding-right:2px;text-align:center;">{{ jogador.jogos }}</td>
                            <td style="padding-left:2px;padding-right:2px;text-align:center;">{{ jogador.vitorias }}</td>
                            <td style="padding-left:2px;padding-right:2px;text-align:center;">{{ jogador.empates }}</td>
                            <td style="padding-left:2px;padding-right:2px;text-align:center;">{{ jogador.derrotas }}</td>
                            <td style="padding-left:2px;padding-right:2px;text-align:center;">{{ jogador.golos }}</td>
                            <td style="padding-left:2px;padding-right:2px;text-align:center;">{{ jogador.assistencias }}</td>
                            <td style="padding-left:3px;padding-right:3px;text-align:center;"><b>{{ jogador.pontuacao }}</b></td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
        {% else %}
            Sem dados para mostrar!
        {% endif %}
        </div>
    </div>
</div>
</div>
<div class="row">
<div class="col-sm-4">
    <div class="panel panel-default">
        <div class="panel-heading">Últimos Jogos</div>
        <div class="panel-body">
        {% if lista_jogos %}
            {% for jogo in lista_jogos %}
                <a href="{% url 'futebola:jogo' jogo.jogo_id %}">{{ jogo }}</a><br>
            {% endfor %}
        {% else %}
            Sem dados para mostrar!
        {% endif %}
        </div>
    </div>
</div>
<div class="col-sm-4">
    <div class="panel panel-default">
        <div class="panel-heading">Próximos Jogos</div>
        <div class="panel-body">
        {% if lista_prox_jogos %}
            {% for jogo in lista_prox_jogos %}
                <a href="{% url 'futebola:jogo' jogo.jogo_id %}">{{ jogo }}</a><br>
            {% endfor %}
        {% else %}
            Sem dados para mostrar!
        {% endif %}
        </div>
    </div>
</div>
<div class="col-sm-4">
    <div class="panel panel-default">
        <div class="panel-heading">Mais Regular</div>
        <div class="panel-body">
        {% if lista_jog_mais_reg %}
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>Nome</th>
                            <th>Jogos</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for jogador in lista_jog_mais_reg %}
                        <tr>
                            <td>{{ jogador.nome }}</td>
                            <td>{{ jogador.jogos }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
        {% else %}
            Sem dados para mostrar!
        {% endif %}
        </div>
    </div>
</div>
</div>
<div class="row">
<div class="col-sm-4">
    <div class="panel panel-default">
        <div class="panel-heading">Clube Mais Representado</div>
        <div class="panel-body">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Clube</th>
                        <th>Jogadores</th>
                    </tr>
                </thead>
                <tbody>
                    {% for clube in lista_clubes %}
                    <tr>
                        {% for item in clube %}
                        <td>{{ item }}</td>
                        {% endfor %}
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
<div class="col-sm-4">
    <div class="panel panel-default">
        <div class="panel-heading">Melhor Marcador</div>
        <div class="panel-body">
        {% if lista_jog_mais_reg %}
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>Nome</th>
                            <th>Golos</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for jogador in lista_jog_mais_gol %}
                        <tr>
                            <td>{{ jogador.nome }}</td>
                            <td>{{ jogador.golos }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
        {% else %}
            Sem dados para mostrar!
        {% endif %}
        </div>
    </div>
</div>
<div class="col-sm-4">
    <div class="panel panel-default">
        <div class="panel-heading">Mais Assistências</div>
        <div class="panel-body">
        {% if lista_jog_mais_reg %}
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>Nome</th>
                            <th>Assis.</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for jogador in lista_jog_mais_ass %}
                        <tr>
                            <td>{{ jogador.nome }}</td>
                            <td>{{ jogador.assistencias }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
        {% else %}
            Sem dados para mostrar!
        {% endif %}
        </div>
    </div>
</div>
<!--<div class="col-sm-8">
    <div class="panel panel-default">
        <div class="panel-heading">Médias</div>
        <div class="panel-body" style="overflow-x: scroll;">
            <table class="table">
                <tr>
                    <td style="text-align: center;">
                        <span class="label label-success">Média de Idades</span><br>
                        {{ media_idades }}
                    </td>
                    <td style="text-align: center;">
                        <span class="label label-primary">Média de Golos/Jogo</span><br>
                        {{ media_golos_jogo }}
                    </td>
                    <td style="text-align: center;">
                        <span class="label label-warning">Média de Golos/Jogador</span><br>
                        {{ media_golos_jogador }}
                    </td>
                    <td style="text-align: center;">
                        <span class="label label-default">Média de Assist./Jogador</span><br>
                        {{ media_assist_jogador }}
                    </td>
                </tr>
            </table>
        </div>
    </div>
</div>-->
</div>
{% endblock %}

futebola/templates/futebola/jogador.html
{% extends "futebola/layout.html" %}
{% load jogador_extras %}
{% block content %}
<div class="row">
    <div class="col-sm-10 col-sm-offset-1">
    <div class="panel panel-default">
        <div class="panel-body">
        {% if jogador %}
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th colspan="6" style="text-align: left;"><h3 style="margin-top: 10px;">{{ jogador }}</h3></th>
                        </tr>
                    </thead>
                    <tbody>
													{% if jogador.foto %}
												<tr>
														<td style="text-align: center;" colspan="2"><img class="img-responsive" style="max-width:150px;margin: auto;" src="{{ jogador.foto.url }}"></td>
												</tr>
													{% endif %}
                        <tr>
                            <td style="font-weight: bold">Data de Nascimento:</td>
                            <td>{{ jogador.data_nascimento|date:"d-m-Y" }}</td>
                        </tr>
                        <tr>
                            <td style="font-weight: bold">Idade:</td>
                            <td>{{ jogador.idade }}</td>
                        </tr>
                        <tr>
                            <td style="font-weight: bold">Clube:</td>
                            <td>{{ jogador.clube_favorito }}</td>
                        </tr>
                    </tbody>
                </table>
        {% else %}
            Sem dados para mostrar!
        {% endif %}
        </div>
    </div>
    <div class="panel panel-default">
        <div class="panel-heading">Estatísticas</div>
        <div class="panel-body">
                <table class="table table-striped">
                   <thead>
                        <tr>
                            <th style="text-align:center;">Época</th>
                            <th style="text-align:center;">Jgs</th>
														<th style="text-align:center;">Vit</th>
														<th style="text-align:center;">Gls</th>
														<th style="text-align:center;">Ass</th>
														<th style="text-align:center;">Pts</th>
                        </tr>
                    </thead>
                    <tbody>
											{% for epoca in epocas_obj %}
                        <tr>
                            <td style="text-align:center;font-weight: bold">{{ epoca.numeracao_epoca }}</td>
														<td style="text-align:center;">{{ jogador|jogos:epoca.numeracao_epoca }}</td>
														<td style="text-align:center;">{{ jogador|vitorias:epoca.numeracao_epoca }}</td>
														<td style="text-align:center;">{{ jogador|golos:epoca.numeracao_epoca }}</td>
														<td style="text-align:center;">{{ jogador|assistencias:epoca.numeracao_epoca }}</td>
														<td style="text-align:center;font-weight: bold">{{ jogador|pontuacao:epoca.numeracao_epoca }}</td>
                        </tr>
											{% endfor %}
											  <tr>
                          <td style="text-align:center;font-weight: bold">TOTAL</td>
                          <td style="text-align:center;font-weight: bold">{{ jogador.jogos }}</td>
													<td style="text-align:center;font-weight: bold">{{ jogador.vitorias }}</td>
													<td style="text-align:center;font-weight: bold">{{ jogador.golos }}</td>
													<td style="text-align:center;font-weight: bold">{{ jogador.assistencias }}</td>
													<td style="text-align:center;font-weight: bold">--</td>
												</tr>
                    </tbody>
                </table>
        </div>
    </div>
    <div class="panel panel-default">
        <div class="panel-heading">Últimos Jogos da Época Atual</div>
        <div class="panel-body" style="text-align:center;">
        {% if lista_jogos %}
            {% for jogo in lista_jogos %}
                <a href="{% url 'futebola:jogo' jogo.jogo_id %}">{{ jogo }}</a><br>
            {% endfor %}
        {% else %}
            Sem dados para mostrar!
        {% endif %}
        </div>
    </div>
</div>
</div>
{% endblock %}

futebola/templates/futebola/penalizacoes.html
{% extends "futebola/layout.html" %}

{% block content %}
<div class="row">
    <div class="col-sm-12">
    <div class="panel panel-default">
        <div class="panel-heading">Penalizações</div>
        <div class="panel-body" style="overflow-y: scroll; height: 400px; padding:0;">
        {% if penalizacoes %}
                <table class="table table-striped table-responsive" style="margin-bottom:0px;border:0;">
                    <thead>
                        <tr>
                            <th style="padding-left:2px;padding-right:2px;text-align:center;">Data</th>
                            <th style="padding-left:2px;padding-right:2px;">Jogador</th>
                            <th style="padding-left:2px;padding-right:2px;text-align:center;">Motivo</th>
                            <th style="padding-left:2px;padding-right:2px;text-align:center;">Valor</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for penalizacao in penalizacoes %}
                        <tr>
                            <td style="padding-left:2px;padding-right:2px;text-align:center;">{{ penalizacao.data }}</td>
                            <td style="padding-left:2px;padding-right:2px;"><a href="{% url 'futebola:jogador' penalizacao.jogador.jogador_id %}">{{ penalizacao.jogador }}</a></td>
                            <td style="padding-left:2px;padding-right:2px;text-align:center;">{{ penalizacao.motivo }}</td>
                            <td style="padding-left:2px;padding-right:2px;text-align:center;">-{{ penalizacao.valor }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
        {% else %}
            Sem dados para mostrar!
        {% endif %}
        </div>
    </div>
</div>
</div>
{% endblock %}